"""initial_aip_schema

Revision ID: 4235831c9a1a
Revises: 
Create Date: 2026-04-22 02:42:33.428706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4235831c9a1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS aip")
    op.create_table('aerodrome',
    sa.Column('icao_code', sa.String(length=4), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_ft', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='aip'
    )
    op.create_index(op.f('ix_aip_aerodrome_icao_code'), 'aerodrome', ['icao_code'], unique=True, schema='aip')
    op.create_table('runway',
    sa.Column('aerodrome_id', sa.UUID(), nullable=False),
    sa.Column('designator', sa.String(length=10), nullable=False),
    sa.Column('length_m', sa.Integer(), nullable=False),
    sa.Column('width_m', sa.Integer(), nullable=True),
    sa.Column('surface_type', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aerodrome_id'], ['aip.aerodrome.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='aip'
    )
    op.create_index(op.f('ix_aip_runway_aerodrome_id'), 'runway', ['aerodrome_id'], unique=False, schema='aip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aip_runway_aerodrome_id'), table_name='runway', schema='aip')
    op.drop_table('runway', schema='aip')
    op.drop_index(op.f('ix_aip_aerodrome_icao_code'), table_name='aerodrome', schema='aip')
    op.drop_table('aerodrome', schema='aip')
    # ### end Alembic commands ###
